services:
  - type: web
    name: proyectoairquality-aguachica
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py api  # âœ… Ahora incluye scheduler
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://airquality_db_cfeb_user:worW2BCeHKf6jwFnrWyiPXnG57ztPf6k@dpg-d4ah0iruibrs73cdpdd0-a.oregon-postgres.render.com/airquality_db_cfeb
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: PORT
        value: 5000

databases:
  - name: airquality-db
    databaseName: air_quality_db
    user: airquality_user